#!/bin/sh

# simple screenshot script using grim and slurp

set -x 
region=$(slurp)

choice=$(printf "Clipboard\nFile" |  wmenu "$@" -p 'Save to')
if [ ! -z "$region" ]; then
    case $choice in
      "Clipboard") grim -g "$region" - | wl-copy ;;
      "File") 
        filename=$(printf '' | wmenu "$@" -p "Enter file name") 
        if [ -z "$filename" ]; then
            filename="$(date +%Y-%m-%d_%H-%M-%S).png"
        fi
        if [ -n "$filename" ]; then
          grim -g "$region" "$HOME/Pictures/screenshots/$filename.png" 
        fi ;;
      *) exit 1 ;;
    esac
else
    case $choice in
      "Clipboard") grim - | wl-copy ;;
      "File") 
        filename=$(printf '' | wmenu "$@" -p "Enter file name") 
        if [ -z "$filename" ]; then
            filename="$(date +%Y-%m-%d_%H-%M-%S).png"
        fi
        if [ -n "$filename" ]; then
          grim  "$HOME/Pictures/screenshots/$filename.png"
        fi ;;
      *) exit 1 ;;
    esac
fi
