#!/bin/sh

# simple screenshot script using grim and slurp

mkdir -p "$HOME/Pictures/screenshots/"

choice=$(printf "Select Area\nFull Screen" | wmenu "$@" -p 'Screenshot Mode')
[ -z "$choice" ] && exit 1  

case $choice in
  "Select Area") 
    use_slurp=true 
    slurp=$(slurp) 
    [ -z "$slurp" ] && exit 1
    ;;
  "Full Screen") use_slurp=false ;;
  *) exit 1;
esac

choice=$(printf "Clipboard\nFile" |  wmenu "$@" -p 'Save to')

case $use_slurp in
  "true") 
    case $choice in
      "Clipboard") grim -g "$slurp" - | wl-copy ;;
      "File") 
        filename=$(printf '' | wmenu "$@" -p "Enter file name") 
        if [ -z "$filename" ]; then
            filename="$(date +%Y-%m-%d_%H-%M-%S).png"
        fi
        if [ -n "$filename" ]; then
          grim -g "$slurp" "$HOME/Pictures/screenshots/$filename.png" 
        fi ;;
      *) exit 1 ;;
    esac ;;

  "false")
    case $choice in
      "Clipboard") grim - | wl-copy ;;
      "File") 
        filename=$(printf '' | wmenu "$@" -p "Enter file name") 
        if [ -z "$filename" ]; then
            filename="$(date +%Y-%m-%d_%H-%M-%S).png"
        fi
        if [ -n "$filename" ]; then
          grim  "$HOME/Pictures/screenshots/$filename.png"
        fi ;;
      *) exit 1 ;;
    esac ;;
esac
