#!/bin/sh
# wmenu-drun - Simple wmenu application launcher written in POSIX sh

get_apps() {
  # set XDG_DATA_HOME and XDG_DATA_DIRS if they are not set
  XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
  XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/share:/usr/local/share}"

  OLD_IFS=$IFS
  IFS=:
  dirs="$XDG_DATA_HOME:$XDG_DATA_DIRS"

  for dir in $dirs
  do
    app_dir="$dir/applications"
    ! [ -d "$app_dir" ] && continue
    
    find "$app_dir" -name "*.desktop" | while IFS= read -r app
    do
      app_id="${app#"$app_dir/"}"
      app_id="$(printf "%s" "$app_id" | tr "/" "-")"
      printf "%s\t%s\n" "$app_id" "$app"
    done 
  done | awk -F '\t' '!seen[$1]++ {print $2}'

  IFS=$OLD_IFS
}

parse_entry(){
  file=$1
  type="" exec="" name="" nodisplay="" hidden="" terminal="false"
eval "$(awk '
    /^\[/{s=0}
    /^\[Desktop Entry\]/{s=1}
    s {
        i = index($0, "=")
        key = substr($0, 1, i-1)
        val = substr($0, i+1)
    }
    s && key=="Name"      {name=val}
    s && key=="Type"      {type=val}
    s && key=="Exec"      {exec=val}
    s && key=="Hidden"    {hidden=val}
    s && key=="NoDisplay" {nodisplay=val}
    s && key=="Terminal"  {terminal=val}
    END {printf "name=\"%s\" type=\"%s\" exec=\"%s\" hidden=\"%s\" nodisplay=\"%s\" terminal=\"%s\"\n", name, type, exec, hidden, nodisplay, terminal}
' "$file")"

exec=$(printf '%s' "$exec" | sed 's/%[fFuUck]//g; s/%i//g') #clean the temp flag
  [ "$type" = "Application" ] || return 1
  [ -n "$exec" ] || return 1
  [ "$nodisplay" = "true" ] && return 1
  [ "$hidden" = "true" ] && return 1
  printf "%s\t%s\t%s\n" "$name" "$exec" "$terminal"
}

entries=$(get_apps | while IFS= read -r app; do
    parse_entry "$app"
done)

choice=$(printf '%s\n' "$entries" | awk -F'\t' '{print $1}' | sort | wmenu "$@" )

[ -z "$choice" ] && exit 0

cmd=$(printf '%s\n' "$entries" | awk -F'\t' -v name="$choice" '$1==name {print $2; exit}')
terminal=$(printf '%s\n' "$entries" | awk -F'\t' -v name="$choice" '$1==name {print $3; exit}')

if [ "$terminal" = "true" ]; then
    cmd="foot -e $cmd"
fi

nohup sh -c "$cmd" > /dev/null 2>&1 &
IFS=$OLD_IFS
