#!/bin/sh

# simple screenshot script using grim and slurp

set -x 
region=$(slurp)
mkdir -p "$HOME/Pictures/screenshots"

choice=$(printf "Clipboard\nFile" |  wmenu "$@" -p 'Save to')
if [ ! -z "$region" ]; then
    case $choice in
      "Clipboard") grim -g "$region" - | wl-copy --type image/png;;
      "File") 
          filename="$(date +%Y-%m-%d_%H-%M-%S).png"
          grim -g "$region" "$HOME/Pictures/screenshots/$filename" 
        ;;
      *) exit 1 ;;
    esac
fi
