#!/bin/sh
# wmenu-drun - Simple wmenu application launcher written in POSIX sh
set -x
term=foot
get_apps() {
    # set directory that we search for .desktop file
    XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
    XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/share:/usr/local/share}"

    OLD_IFS=$IFS
    IFS=:
    dirs="$XDG_DATA_HOME:$XDG_DATA_DIRS"

    # find .desktop in XDG_DATA_HOME and XDG_DATA_DIRS
    # print app_dir and full path separated by \t for parsing app_id
    # increment gawk array[app_id] for avoiding duplicate app_id
    for dir in $dirs; do
        app_dir="$dir/applications"
        [ -d "$app_dir" ] && find "$app_dir" -name "*.desktop" | sed "s|^|$app_dir\t|"
    done | gawk -F'\t' '{
        app_dir=$1; path=$2
        app_id=substr(path, length(app_dir)+2)
        gsub(/\//, "-", app_id)
        if (!seen[app_id]++) print path
    }'
    IFS=$OLD_IFS
}

# detect the ENDFILE for pasing each entry
# name, type, exec, hidden, nodisplay and terminal by selecing everything after first '='
# clean exec field removing %f %F %u %U %c %k
# print name, exec, terminal separeated by tab
entries=$(get_apps | xargs -d '\n' gawk '
    FNR==1 {s=0; name=""; type=""; exec=""; hidden=""; nodisplay=""; terminal=""}
    /^\[/{s=0}
    /^\[Desktop Entry\]/{s=1}
    s {
        i = index($0, "=")
        key = substr($0, 1, i-1)
        val = substr($0, i+1)
        gsub(/^[ \t]+|[ \t]+$/, "", key)
        gsub(/^[ \t]+|[ \t]+$/, "", val)
        if (key=="Name")      name=val
        if (key=="Type")      type=val
        if (key=="Exec")      exec=val
        if (key=="Hidden")    hidden=val
        if (key=="NoDisplay") nodisplay=val
        if (key=="Terminal")  terminal=val
    }
    ENDFILE {
        if (type=="Application" && exec!="" && nodisplay!="true" && hidden!="true") {
            gsub(/%[fFuUck]/, "", exec)
            gsub(/%i/, "", exec)
            printf "%s\t%s\t%s\n", name, exec, terminal
        }
    }
')

#print only name to wmenu & also sort by alphabetical order
choice=$(printf '%s\n' "$entries" | cut  -f 1 | sort | wmenu "$@" )

[ -z "$choice" ] && exit 0

# pasing cmd base on returned name, exec, terminal
cmd=$(printf '%s\n' "$entries" | gawk -F'\t' -v name="$choice" '$1==name {print $2; exit}')
terminal=$(printf '%s\n' "$entries" | gawk -F'\t' -v name="$choice" '$1==name {print $3; exit}')

if [ "$terminal" = "true" ]; then
    cmd="$term -e $cmd"
fi

nohup sh -c "$cmd" > /dev/null 2>&1 &
IFS=$OLD_IFS
